language: python
python:
  - 2.7
install:
  - ( cd client && npm install --quiet --no-spin )
  - ( cd client && bower install --quiet )
  - pip install tox
  - pip install coveralls
  - gem install coveralls-lcov
script:
  - ( cd client && karma start --single-run --browsers PhantomJS --reporters dots,coverage )
  - tox -c radar/tox.ini
  - tox -c api/tox.ini
after_success:
  - ( cd client && coveralls-lcov -n -v coverage/*/lcov.info > coveralls.json)
  - coverage combine radar/.coverage api/.coverage
  - coveralls --merge=client/coveralls.json
