language: python
python:
  - 2.7
install:
  - npm install -g npm@3
  - ( cd client && npm install --quiet --no-spin )
  - ( cd client && bower install --quiet )
  - pip install tox
  - pip install coveralls
  - gem install coveralls-lcov
script:
  - ( cd client && karma start --single-run --browsers PhantomJS --reporters dots,coverage )
  - tox -c radar/tox.ini
  - tox -c api/tox.ini
after_success:
  - coveralls-lcov -n -v <(cat client/coverage/*/lcov.info) > client/coveralls.json
  - coverage combine radar/.coverage api/.coverage
  - coveralls --merge=client/coveralls.json
