---
- name: create the radar database
  postgresql_db: name=radar
  become: yes
  become_user: postgres

- name: add the uuid-ossp extension to radar
  postgresql_ext: name=uuid-ossp db=radar
  become: yes
  become_user: postgres

- name: create the radar postgresql user
  postgresql_user: db=radar name=radar password={{ db_password }}
  become: yes
  become_user: postgres
