---
- name: install the postgresql repo
  yum: name=http://yum.postgresql.org/9.4/redhat/rhel-7-x86_64/pgdg-centos94-9.4-1.noarch.rpm state=present

- name: install postgresql
  yum: name={{ item }} state=present
  with_items:
    - postgresql94-server
    - postgresql94-devel
    - postgresql94-contrib

- name: create postgresql data directory
  command: /usr/pgsql-9.4/bin/postgresql94-setup initdb creates=/var/lib/pgsql/9.4/data/PG_VERSION

- name: pg_hba.conf
  template: src=pg_hba.conf dest=/var/lib/pgsql/9.4/data/pg_hba.conf owner=postgres group=postgres mode=0700
  notify:
    - restart postgresql

- name: postgresql.conf
  template: src=postgresql.conf dest=/var/lib/pgsql/9.4/data/postgresql.conf owner=postgres group=postgres mode=0700
  notify:
    - restart postgresql

- name: start and enable postgresql
  service: name=postgresql-9.4 state=started enabled=yes

- name: install psycopg2
  yum: name=python-psycopg2 state=present

# Allows checking to see if an encrypted password has changed
- name: install passlib
  yum: name=python-passlib state=present

- name: create the radar database
  postgresql_db: name=radar
  become: yes
  become_user: postgres

- name: add the uuid-ossp extension
  postgresql_ext: name=uuid-ossp db=radar

- name: create the radar postgresql user
  postgresql_user: db=radar name=radar
  become: yes
  become_user: postgres
  when: "'vagrant' not in group_names"

- name: set the password for the postgres postgresql user (vagrant)
  postgresql_user: name=postgres password=vagrant
  become: yes
  become_user: postgres
  when: "'vagrant' in group_names"

- name: create the radar postgresql user (vagrant)
  postgresql_user: db=radar name=radar password=vagrant
  become: yes
  become_user: postgres
  when: "'vagrant' in group_names"

- name: create the vagrant postgresql user (vagrant)
  postgresql_user: db=radar name=vagrant password=vagrant
  become: yes
  become_user: postgres
  when: "'vagrant' in group_names"
