---
- name: install epel repo
  yum: name=epel-release state=present

- name: install common packages
  yum: name={{ item }} state=present
  with_items:
    - vim
    - git
    - htop
    - man

- name: install development tools
  yum: name='@Development Tools' state=present
