---
- name: SELinux permissive mode
  selinux: policy=targeted state=permissive

- name: install epel repo
  yum: name=epel-release state=present

- name: install common packages
  yum: name={{ item }} state=present
  with_items:
    - vim
    - git
    - htop
    - man

- name: install development tools
  yum: name='@Development Tools' state=present

- name: install ruby
  yum: name={{ item }} state=present
  with_items:
    - ruby
    - ruby-devel
    - rubygems

- name: install fpm
  gem: name=fpm user_install=no state=present

- name: create radar group
  group: name=radar state=present

- name: create radar user
  user: name=radar groups=radar home=/ shell=/sbin/nologin system=yes state=present

- name: create vagrant user
  user: name=vagrant group=vagrant groups=radar home=/home/vagrant shell=/bin/bash state=present

- name: vagrant home
  file: path=/home/vagrant state=directory owner=vagrant group=vagrant mode=0755

- name: .bashrc for vagrant
  template: src=bashrc dest=/home/vagrant/.bashrc owner=vagrant group=vagrant mode=0644

- name: .bash_profile for vagrant
  template: src=bash_profile dest=/home/vagrant/.bash_profile owner=vagrant group=vagrant mode=0644
