---
- name: vagrant .bashrc
  template: src=bashrc.j2 dest=/home/vagrant/.bashrc owner=vagrant group=vagrant mode=0644

- name: vagrant .bash_profile
  template: src=bash_profile.j2 dest=/home/vagrant/.bash_profile owner=vagrant group=vagrant mode=0644
