---
- name: install nodejs
  yum: name=nodejs state=present

# python 2.7.5 doesn't support SNI so we have to disable certificate validation
- name: download npm install script
  get_url: url=https://www.npmjs.com/install.sh dest=/tmp/install_npm.sh validate_certs=False

- name: install npm
  command: sh /tmp/install_npm.sh creates=/usr/bin/npm

- name: set registry
  npm_config: key=registry value=https://registry.npmjs.org/

- name: set bin-links
  npm_config: key=bin-links value=false

# globalconfig locations:
# root = /etc/npmrc
# vagrant = /usr/etc/npmrc

# Update vagrant's globalconfig to /etc/npmrc (defaults to /usr/etc/npmrc otherwise)
- name: set globalconfig for vagrant
  npm_config: key=globalconfig value=/etc/npmrc
  become: yes
  become_user: vagrant
