---
- name: install nodejs
  yum: name=nodejs state=present

# NOTE
# Older versions of npm put each module's dependencies in a node_modules
# sub-directory which can create some very long paths.
# On Windows these paths can exceed the maximum path length.
# If you run npm install from Windows it's not a problem (it can create paths
# too long to delete from explorer though).
# If you run npm install from a VM on a Windows host you'll run into the
# maximum path length issue.
# npm 3+ will only create nested node_modules directories if the module
# requires anorther version of a library.
# The shell script from npmjs.org installs the latest version of npm
# (currently 3.x vs the packaged version of 1.x).
# FIXME https://www.virtualbox.org/ticket/11976
# python 2.7.5 doesn't support SNI so we have to disable certificate validation
- name: download npm install script
  get_url: url=https://www.npmjs.com/install.sh dest=/tmp/install_npm.sh validate_certs=False

- name: install npm
  command: sh /tmp/install_npm.sh creates=/usr/bin/npm

# Use an alternative registry (e.g npm-lazy-proxy) if specified
- name: set registry
  npm_config: key=registry value={{ npm_registry }} global=yes

# NOTE the bin-links option prevents npm from symlinking any binaries.
# VirtualBox supports symlinks if the SharedFoldersEnableSymlinksCreate option
# is enabled. In Windows you need to have the SeCreateSymbolicLinkPrivilege
# privilege to create symlinks.
# http://security.stackexchange.com/questions/10194
- name: disable bin-links for vagrant
  npm_config: key=bin-links value={{ npm_bin_links }}
  become: yes
  become_user: vagrant

# globalconfig locations:
# root = /etc/npmrc
# vagrant = /usr/etc/npmrc

# Update vagrant's globalconfig to /etc/npmrc (defaults to /usr/etc/npmrc otherwise)
- name: set globalconfig for vagrant
  npm_config: key=globalconfig value=/etc/npmrc
  become: yes
  become_user: vagrant
