---
- name: install postgresql
  yum: name={{ item }} state=present
  with_items:
  - postgresql94
  - postgresql94-libs
  - postgresql94-devel

- name: create .pip directory
  file: path=/home/vagrant/.pip owner=vagrant group=vagrant mode=0755 state=directory

- name: set index-url
  ini_file: dest=/home/vagrant/.pip/pip.conf section=global option=index-url value={{ pip_index_url }}
  become: yes
  become_user: vagrant

- name: set trusted-host
  ini_file: dest=/home/vagrant/.pip/pip.conf section=global option=trusted-host value={{ pip_trusted_host }}
  become: yes
  become_user: vagrant

- name: install virtualenv
  yum: name=python-virtualenv state=present

- name: install packaging dev-requirements.txt
  pip: virtualenv={{ virtualenv_path }} requirements=dev-requirements.txt chdir={{ src_path }}/packaging
  become: yes
  become_user: vagrant

- name: install radar-api dev-requirements.txt
  pip: virtualenv={{ virtualenv_path }} requirements=dev-requirements.txt chdir={{ src_path }}/api
  become: yes
  become_user: vagrant
  environment:
    PATH: '/usr/pgsql-9.4/bin:/usr/local/bin:/usr/bin:/bin'

- name: install radar-mock-ukrdc dev-requirements.txt
  pip: virtualenv={{ virtualenv_path }} requirements=dev-requirements.txt chdir={{ src_path }}/mock_ukrdc
  become: yes
  become_user: vagrant
  environment:
    PATH: '/usr/pgsql-9.4/bin:/usr/local/bin:/usr/bin:/bin'

- name: install radar dev-requirements.txt
  pip: virtualenv={{ virtualenv_path }} requirements=dev-requirements.txt chdir={{ src_path }}/radar
  become: yes
  become_user: vagrant

- name: install radar
  pip: virtualenv={{ virtualenv_path }} name=. extra_args="--no-deps --editable" chdir={{ src_path }}/radar
  become: yes
  become_user: vagrant

- name: install radar-api
  pip: virtualenv={{ virtualenv_path }} name=. extra_args="--no-deps --editable" chdir={{ src_path }}/api
  become: yes
  become_user: vagrant

- name: install radar-mock-ukrdc
  pip: virtualenv={{ virtualenv_path }} name=. extra_args="--no-deps --editable" chdir={{ src_path }}/mock_ukrdc
  become: yes
  become_user: vagrant
