---
- name: create the config directory
  file: path={{ api_dev_config_path }} state=directory

- name: create systemd service
  template: src=systemd dest={{ api_dev_systemd_path }} owner=root group=root mode=0755
  notify:
    - reload systemd

- name: create settings.py
  template: src=settings.py dest={{ api_dev_settings_path }} owner=root group=root mode=0644

- name: create uwsgi.ini
  template: src=uwsgi.ini dest={{ api_dev_uwsgi_path }} owner=root group=root mode=0644

- name: create secret key
  shell: dd if=/dev/urandom bs=1 count=32 | base64 > {{ api_dev_secret_key_path }}
  args:
    creates: "{{ api_dev_secret_key_path }}"

- name: set permissions on secret key
  file: path={{ api_dev_secret_key_path }} state=file owner=root group=radar mode=640
