---
- name: install radar-mock-ukrdc
  yum: name=radar-mock-ukrdc state=latest

- name: create settings.py
  template: src=settings.py dest={{ mock_ukrdc_settings_path }} owner=root group=root mode=0644
  notify:
    - restart radar-mock-ukrdc

- name: create uwsgi.ini
  template: src=uwsgi.ini dest={{ mock_ukrdc_uwsgi_path }} owner=root group=root mode=0644
  notify:
    - restart radar-mock-ukrdc

- name: start and enable radar-mock-ukrdc
  service: name=radar-mock-ukrdc state=started enabled=yes
