---
- name: create dhparam.pem
  command: openssl dhparam -out /etc/pki/tls/certs/dhparam.pem 2048
  args:
    creates: /etc/pki/tls/certs/dhparam.pem

- name: nginx includes
  template: src={{ item }} dest=/etc/nginx/{{ item }} owner=root group=root mode=0644
  with_items:
    - radar_web_headers
    - radar_web_no_cache
    - radar_web_proxy
    - radar_web_ssl
  notify:
    - restart nginx

- name: nginx config
  template: src=nginx.conf dest=/etc/nginx/conf.d/radar-web.conf owner=root group=root mode=0644
  notify:
    - restart nginx
