---
- hosts:
    - staging
    - production
  roles:
    - repo

- hosts: web
  become: yes
  roles:
    - web
    - mock_ukrdc

- hosts: db
  become: yes
  roles:
    - db

- hosts: dev
  become: yes
  vars:
    src_path: /home/vagrant/src
    virtualenv_path: /home/vagrant/venv
  roles:
    - mock_ukrdc_dev
    - db_dev
    - web_dev
