---
- name: install {{ api_name }}
  yum: name={{ api_name }} state=latest

- name: create settings.py
  template: src=settings.py dest={{ api_settings_path }} owner=root group=root mode=0644
  notify:
    - restart api

- name: create uwsgi.ini
  template: src=uwsgi.ini dest={{ api_wsgi_path }} owner=root group=root mode=0644
  notify:
    - restart api

- name: create secret key
  command: dd if=/dev/urandom of={{ api_secret_key_path }} bs=1 count=32
  args:
    creates: "{{ api_secret_key_path }}"

- name: set permissions on secret key
  file: path={{ api_secret_key_path }} state=file owner=root group=radar mode=640

- name: start and enable {{ api_name }}
  service: name={{ api_name }} state=started enabled=yes
